adds Gantry-backed logging to the text-recognizer

diff --git a/app_gradio/Dockerfile b/app_gradio/Dockerfile
--- a/app_gradio/Dockerfile
+++ b/app_gradio/Dockerfile
@@ -3,19 +3,22 @@
 FROM python:3.7-buster
 
 # Create the working directory
+#   set -x prints commands and set -e causes us to stop on errors
 RUN set -ex && mkdir /repo
 WORKDIR /repo
 
 # Install Python dependencies
-COPY requirements.txt ./requirements.txt
+COPY requirements/prod.txt ./requirements.txt
 RUN pip install --upgrade pip==21.1.3
 RUN pip install -r requirements.txt
+ENV PYTHONPATH ".:"
 
 # Copy only the relevant directories
+#   note that we use a .dockerignore file to avoid copying logs etc.
 COPY text_recognizer/ ./text_recognizer
 COPY app_gradio/ ./app_gradio
+COPY ./.aws/config ./.aws/config
 
-# Run the web server
-EXPOSE 11700
-ENV PYTHONPATH /repo
-ENTRYPOINT ["python3", "/repo/app_gradio/app.py", "--port", "11700"]
+# Use docker run -it --rm -p$PORT:11717 to run the web server and listen on host $PORT
+#   add --help top see help for the Python script
+ENTRYPOINT ["python3", "app_gradio/app.py", "--port", "11717"]
